export const metadata = {
  title:"Explore | Create",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <>
      {children}
    </>
  )
}

export default Layout
